name: "Fraser Lab"
description: "This is the official web page for the James Fraser Lab at UCSF."

url: "http://fraserlab.com"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

defaults:
  - scope:
      type: members
    values:
      layout: member

collections:
        affiliates:
                output: true
        members:
                output: true
                permalink: /member/:name/
        publications:
                output: true
        reviews:
                output: true
        alumni:
                output: true
        sep:
                output: true
        visitors:
                output: true
        undergrads:
                output: true
        pets:
                output: true
